// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nguyencongthang_231230913_de01.Models;

#nullable disable

namespace nguyencongthang_231230913_de01.Migrations
{
    [DbContext(typeof(ComputerDbContext))]
    [Migration("20251024011550_nctComputer")]
    partial class nctComputer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nguyencongthang_231230913_de01.Models.nctComputer", b =>
                {
                    b.Property<int?>("nctComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("nctComId"));

                    b.Property<string>("nctComImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nctComName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("nctComPrice")
                        .HasColumnType("float");

                    b.Property<bool?>("nctComStatus")
                        .HasColumnType("bit");

                    b.HasKey("nctComId");

                    b.ToTable("nctComputers");
                });
#pragma warning restore 612, 618
        }
    }
}
